var adsconf = { 
    currentPage: "", 
    targeting: { }, 
    amazon: { pubID: "3309" },  
    "pagesSlots": { 
        "/120157152/MILLENIUM_FR_WEB/_default":{
            "header":{
                "targeting":{},
                "amazonConfig":{
                    "slotID":"header",
                    "slotName":"millenium.org_header"},
                    "dfpSizes":{"0":[[1,1],[320,50],[320,100],[300,50],[300,100]],"980":[[1,1],[728,90],[970,90]],"1024":[[1,1],[728,90],[970,90],[970,250],[1000,90]]},
                    "hbSizes":{"banner":{"0":[[320,50],[320,100],[300,50],[300,100]],"980":[[728,90],[970,90]],"1024":[[728,90],[970,90],[970,250],[1000,90],[1800,1000]]}},
                    "prebidConfig":{
                        "bids":[
                            {
                                "bidder":"appnexus",
                                "params":{
                                    "placementId":"4619151"
                                }
                            },
                                {
                                "bidder":"rubicon",
                                "params":{
                                    "accountId":"16072","siteId":"164386","zoneId":"787388"
                                }
                            },{
                                "bidder":"improvedigital",
                                "params":{
                                    "placementId":"22025489"
                                }
                            },{
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[320,50]
                                }
                            },{
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[320,100]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[300,50]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[300,100]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275","size":[728,90]
                                }
                            },{
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[970,90]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":
                                {
                                    "siteId":"270275",
                                    "size":[1000,90]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270275",
                                    "size":[970,250]
                                }
                            },{
                                "bidder":"criteo",
                                "params":{
                                    "networkId":"2929",
                                    "publisherSubId":"millenium.org/header"
                                }
                            }]}
            },
        "rectangle_atf":
        {
            "targeting":{},
            "amazonConfig":{
                "slotID":"rectangle_atf",
                "slotName":"millenium.org_rectangle_atf"
            },
            "dfpSizes":{
                "0":[[1,1],
                [300,250],
                [300,600],
                [320,480]],
                "980":[[1,1],
                [300,250],
                [300,600],
                [120,600],
                [160,600]],
                "1024":[
                    [1,1],
                    [300,250],
                    [300,600],
                    [120,600],
                    [160,600]
                ]
            },
            "hbSizes":{
                "banner":{
                    "0":[
                        [300,250],
                        [300,600],
                        [320,480]],
                    "980":[
                        [300,250],
                        [300,600],
                        [120,600],
                        [160,600]],
                    "1024":[
                        [300,250],
                        [300,600],
                        [120,600],
                        [160,600]]   
                }
            },
            "prebidConfig":{
                "bids":[
                    {
                        "bidder":"appnexus",
                        "params":{
                            "placementId":"4619152"
                        }
                    },
                    {
                        "bidder":"rubicon",
                        "params":{
                            "accountId":"16072",
                            "siteId":"164386",
                            "zoneId":"787388"
                        }
                    },{
                        "bidder":"improvedigital",
                        "params":{
                            "placementId":"22005250"
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"268593",
                            "size":[300,250]
                        }
                    },{
                        "bidder":"ix",
                        "params":{
                            "siteId":"268593",
                            "size":[300,600]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"268593",
                            "size":[320,480]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"268593",
                            "size":[160,600]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"268593",
                            "size":[120,600]
                        }
                    },{
                        "bidder":"criteo",
                        "params":
                        {
                            "networkId":"2929",
                            "publisherSubId":"millenium.org/rectangle_atf"
                        }
                    },
                    {
                        "bidder":"teads",
                        "params":{
                            "placementId":"102589",
                            "pageId":"94751"
                        }
                    },
                    {
                        "bidder":"triplelift",
                        "params":{
                            "inventoryCode":"Webedia_Millenium_MPU_Desktop_ATF"
                        }}
                    ]
                }
            },
            "rectangle_mtf":{
                "targeting":{},
                "amazonConfig":{
                    "slotID":"rectangle_mtf",
                    "slotName":"millenium.org_rectangle_mtf"
                },
                "dfpSizes":{
                    "0":[
                        [1,1],
                        [300,250]
                    ],
                    "980":[
                        [1,1],
                        [300,250],
                        [300,600],
                        [120,600],
                        [160,600]],
                    "1024":[
                        [1,1],
                        [300,250],
                        [300,600],
                        [120,600],
                        [160,600]
                    ]
                },
                "hbSizes":{
                    "banner":{
                        "0":[
                            [300,250]
                        ],
                        "980":[
                            [300,250],
                            [300,600],
                            [120,600],
                            [160,600]
                        ],
                        "1024":[
                            [300,250],
                            [300,600],
                            [120,600],
                            [160,600]
                        ]
                    }
                },
                "prebidConfig":{
                    "bids":[
                        {
                            "bidder":"appnexus",
                            "params":{
                                "placementId":"4619153"
                            }
                        },
                        {
                            "bidder":"rubicon",
                            "params":{
                                "accountId":"16072",
                                "siteId":"164386",
                                "zoneId":"787388"
                            }
                        },{
                            "bidder":"improvedigital",
                            "params":{"placementId":"22005262"
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"270267",
                            "size":
                            [300,250]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"270267",
                            "size":[300,600]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"270267",
                            "size":[160,600]
                        }
                    },
                    {
                        "bidder":"ix",
                        "params":{
                            "siteId":"270267",
                            "size":[120,600]
                        }
                    },
                    {
                        "bidder":"criteo",
                        "params":{
                            "networkId":"2929",
                            "publisherSubId":"millenium.org/rectangle_mtf"
                        }
                    },
                    {
                        "bidder":"triplelift",
                        "params":{
                            "inventoryCode":"Webedia_Millenium_MPU_Desktop_MTF"
                        }
                    }
                ]
            }
        },
        "rectangle_btf":{
            "targeting":{},
            "amazonConfig":{
                "slotID":"rectangle_btf",
                "slotName":"millenium.org_rectangle_btf"
            },
            "dfpSizes":{
                "0":[
                    [1,1],[300,250],[300,600],[320,480]],
                "980":[[1,1],[300,250],[300,600],[120,600],[160,600]],
                "1024":[[1,1],[300,250],[300,600],[120,600],[160,600]]},
                "hbSizes":{
                    "banner":{
                        "0":[[300,250],[300,600],[320,480]],
                        "980":[[300,250],[300,600],[120,600],[160,600]],
                        "1024":[[300,250],[300,600],[120,600],[160,600]]
                    }
                },
                    "prebidConfig":{
                        "bids":[
                            {
                                "bidder":"appnexus",
                                "params":{
                                    "placementId":"4619154"
                                }
                            },
                            {
                                "bidder":"rubicon",
                                "params":{
                                    "accountId":"16072",
                                    "siteId":"164386",
                                    "zoneId":"787392"
                                }
                            },
                            {
                                "bidder":"improvedigital",
                                "params":{
                                    "placementId":"22005187"
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270269",
                                    "size":[300,250]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270269",
                                    "size":[300,600]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270269",
                                    "size":[160,600]
                                }
                            },
                            {
                                "bidder":"ix",
                                "params":{
                                    "siteId":"270269",
                                    "size":[120,600]
                                }
                            },
                            {
                                "bidder":"criteo",
                                "params":{
                                    "networkId":"2929",
                                    "publisherSubId":"millenium.org/rectangle_btf"
                                }
                            },
                            {
                                "bidder":"triplelift",
                                "params":{
                                    "inventoryCode":"Webedia_Millenium_MPU_Desktop_BTF"
                                }
                            }
                        ]
                    }
                },
                "interstitial":{
                    "targeting":{},
                    "dfpSizes":{
                        "0":[[1,1]],
                        "980":[[1,1]],
                        "1024":[[1,1]]
                    }
                },
                "inread1":{
                    "targeting":{},
                    "dfpSizes":{
                        "0":[[1,1],[300,250]],
                        "980":[[1,1],[300,250]],
                        "1024":[[1,1],[300,250]]
                    }
                },
                "inread2":{
                    "targeting":{},
                    "dfpSizes":{
                    "0":[[1,1]],
                    "980":[[1,1]],
                    "1024":[[1,1]]
                }
            }
        }, 
        "/120157152/MILLENIUM_FR_WEB/_default-mobile":
        {
            "header":{
                "targeting":{},
                "amazonConfig":{
                    "slotID":"header",
                    "slotName":"millenium.org_header"
                },
                "dfpSizes":{
                    "0":[[1,1],[320,50],[320,100],[300,50],[300,100]],
                    "980":[[1,1],[728,90],[970,90]],
                    "1024":[[1,1],[728,90],[970,90],[970,250],[1000,90],[1800,1000]]
                },
                "hbSizes":{
                    "banner":{
                        "0":[[320,50],[320,100],[300,50],[300,100]],
                        "980":[[728,90],[970,90]],
                        "1024":[[728,90],[970,90],[970,250],[1000,90],[1800,1000]]
                    }
                },
                "prebidConfig":{
                    "bids":[
                        {
                            "bidder":"appnexus",
                            "params":{
                                "placementId":"13015571"
                            }
                        },
                        {
                            "bidder":"rubicon",
                            "params":{
                                "accountId":"16072",
                                "siteId":"164386",
                                "zoneId":"787388"
                            }
                        },
                        {
                            "bidder":"improvedigital",
                            "params":{
                                "placementId":"22025489"
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[320,50]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[320,100]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[300,50]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[300,100]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[728,90]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[970,90]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[1000,90]
                            }
                        },
                        {
                            "bidder":"ix",
                            "params":{
                                "siteId":"270275",
                                "size":[970,250]
                            }
                        },
                        {
                            "bidder":"criteo",
                            "params":{
                                "networkId":"2929",
                                "publisherSubId":"millenium.org/header"
                            }
                        }
                    ]
                }
            },
            "rectangle_atf":{
                "targeting":{},
                "amazonConfig":{
                    "slotID":"rectangle_atf",
                    "slotName":"millenium.org_rectangle_atf"
                },
                "dfpSizes":{
                    "0":[[1,1],[300,250],[300,600],[320,480]],
                    "980":[[1,1],[300,250],[300,600],[120,600],[160,600]],
                    "1024":[[1,1],[300,250],[300,600],[120,600],[160,600]]},
                    "hbSizes":{
                        "banner":{
                            "0":[[300,250],[300,600],[320,480]],
                            "980":[[300,250],[300,600],[120,600],[160,600]],
                            "1024":[[300,250],[300,600],[120,600],[160,600]]}},
                            "prebidConfig":{
                                "bids":[
                                    {
                                        "bidder":"appnexus",
                                        "params":{
                                            "placementId":"13015575"
                                        }
                                    },
                                    {
                                        "bidder":"rubicon",
                                        "params":{
                                            "accountId":"16072",
                                            "siteId":"164386",
                                            "zoneId":"787388"
                                        }
                                    },
                                    {
                                        "bidder":"improvedigital",
                                        "params":{
                                            "placementId":"22005250"
                                        }
                                    },
                                    {
                                        "bidder":"ix",
                                        "params":{
                                            "siteId":"268593",
                                            "size":[300,250]
                                        }
                                    },
                                    {
                                        "bidder":"ix",
                                        "params":{
                                            "siteId":"268593",
                                            "size":[300,600]
                                        }
                                    },
                                    {
                                        "bidder":"ix",
                                        "params":{
                                            "siteId":"268593",
                                            "size":[320,480]
                                        }
                                    },
                                    {
                                        "bidder":"ix",
                                        "params":{
                                            "siteId":"268593",
                                            "size":[160,600]
                                        }
                                    },
                                    {
                                        "bidder":"ix",
                                        "params":{
                                            "siteId":"268593",
                                            "size":[120,600]
                                        }
                                    },
                                    {
                                        "bidder":"criteo",
                                        "params":{
                                            "networkId":"2929",
                                            "publisherSubId":"millenium.org/rectangle_atf"
                                        }
                                    },
                                    {
                                        "bidder":"teads",
                                        "params":{
                                            "placementId":"102589",
                                            "pageId":"94751"
                                        }
                                    },
                                    {
                                        "bidder":"triplelift",
                                        "params":{
                                            "inventoryCode":"Webedia_Millenium_MPU_Mobile_ATF"
                                        }
                                    }
                                ]
                            }
                        },
                        "rectangle_mtf":{
                            "targeting":{},
                            "amazonConfig":{
                                "slotID":"rectangle_mtf",
                                "slotName":"millenium.org_rectangle_mtf"
                            },
                            "dfpSizes":{
                                "0":[[1,1],[300,250]],
                                "980":[[1,1],[300,250],[300,600],[120,600],[160,600]],
                                "1024":[[1,1],[300,250],[300,600],[120,600],[160,600]]},
                                "hbSizes":{
                                    "banner":{
                                        "0":[[300,250]],
                                        "980":[[300,250],[300,600],[120,600],[160,600]],
                                        "1024":[[300,250],[300,600],[120,600],[160,600]]}},
                                        "prebidConfig":{
                                            "bids":[
                                                {
                                                    "bidder":"appnexus",
                                                    "params":{
                                                        "placementId":"13015587"
                                                    }
                                                },
                                                {
                                                    "bidder":"rubicon",
                                                    "params":{
                                                        "accountId":"16072",
                                                        "siteId":"164386",
                                                        "zoneId":"787388"
                                                    }
                                                },
                                                {
                                                    "bidder":"improvedigital",
                                                    "params":{
                                                        "placementId":"22005262"
                                                    }
                                                },
                                                {
                                                    "bidder":"ix",
                                                    "params":{
                                                        "siteId":"270267",
                                                        "size":[300,250]
                                                    }
                                                },
                                                {
                                                    "bidder":"ix",
                                                    "params":{
                                                        "siteId":"270267",
                                                        "size":[300,600]
                                                    }
                                                },
                                                {
                                                    "bidder":"ix",
                                                    "params":{
                                                        "siteId":"270267",
                                                        "size":[160,600]
                                                    }
                                                },
                                                {
                                                    "bidder":"ix",
                                                    "params":{
                                                        "siteId":"270267",
                                                        "size":[120,600]
                                                    }
                                                },
                                                {
                                                    "bidder":"criteo",
                                                    "params":{
                                                        "networkId":"2929",
                                                        "publisherSubId":"millenium.org/rectangle_mtf"
                                                    }
                                                },
                                                {
                                                    "bidder":"triplelift",
                                                    "params":{
                                                        "inventoryCode":"Webedia_Millenium_MPU_Mobile_MTF"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    "rectangle_btf":{
                                        "targeting":{},
                                        "amazonConfig":{
                                            "slotID":"rectangle_btf",
                                            "slotName":"millenium.org_rectangle_btf"
                                        },
                                        "dfpSizes":{
                                            "0":[[1,1],[300,250],[300,600],[320,480]],
                                            "980":[[1,1],[300,250],[300,600],[120,600],[160,600]],
                                            "1024":[[1,1],[300,250],[300,600],[120,600],[160,600]]},
                                            "hbSizes":{
                                                "banner":{
                                                    "0":[[300,250],[300,600],[320,480]],
                                                    "980":[[300,250],[300,600],[120,600],[160,600]],
                                                    "1024":[[300,250],[300,600],[120,600],[160,600]]}},
                                                    "prebidConfig":{
                                                        "bids":[
                                                            {
                                                                "bidder":"appnexus",
                                                                "params":{
                                                                    "placementId":"13015593"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"rubicon",
                                                                "params":{
                                                                    "accountId":"16072",
                                                                    "siteId":"164386",
                                                                    "zoneId":"787392"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"improvedigital",
                                                                "params":{
                                                                    "placementId":"22005187"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"ix",
                                                                "params":{
                                                                    "siteId":"270269",
                                                                    "size":[300,250]
                                                                }
                                                            },
                                                            {
                                                                "bidder":"ix",
                                                                "params":{
                                                                    "siteId":"270269",
                                                                    "size":[300,600]
                                                                }
                                                            },
                                                            {
                                                                "bidder":"ix",
                                                                "params":{
                                                                    "siteId":"270269",
                                                                    "size":[160,600]
                                                                }
                                                            },
                                                            {
                                                                "bidder":"ix",
                                                                "params":{
                                                                    "siteId":"270269",
                                                                    "size":[120,600]
                                                                }
                                                            },
                                                            {
                                                                "bidder":"criteo",
                                                                "params":{
                                                                    "networkId":"2929",
                                                                    "publisherSubId":"millenium.org/rectangle_btf"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"triplelift",
                                                                "params":{
                                                                    "inventoryCode":"Webedia_Millenium_MPU_Mobile_BTF"
                                                                }
                                                            }
                                                        ]
                                                    }
                                                },
                                                "interstitial":{
                                                    "targeting":{},
                                                    "dfpSizes":{
                                                        "0":[[1,1]],
                                                        "980":[[1,1]],
                                                        "1024":[[1,1]]
                                                    }
                                                },
                                                "inread1":{
                                                    "targeting":{},
                                                    "amazonConfig":{
                                                        "slotID":"inread1",
                                                        "slotName":"millenium.com_inread1"
                                                    },
                                                    "dfpSizes":{
                                                        "0":[[1,1]]
                                                    },
                                                    "hbSizes":{
                                                        "banner":{
                                                            "0":[[300,250]]
                                                        },
                                                            "video":{
                                                                "context":"outstream",
                                                                "playerSize":[640,480]
                                                                }
                                                            },
                                                    "prebidConfig":{
                                                        "bids":[
                                                            {
                                                                "bidder":"appnexus",
                                                                "params":{
                                                                    "placementId":"17355899"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"teads",
                                                                "params":{
                                                                    "placementId":"108365",
                                                                    "pageId":"100057"
                                                                }
                                                            },
                                                            {
                                                                "bidder":"spotx",
                                                                "params":{
                                                                    "channel_id":"245039",
                                                                    "ad_unit":"outstream", /////// YYYYYYYYYOOOOOUUUAAAAARRRREEE there
                                                                    "outstream_options":
                                                                    {
                                                                        "slot":"inread1",
                                                                        "playersize_auto_adapt":"true",
                                                                        "custom_override":{
                                                                            "collapse":0,
                                                                            "click_to_replay":1,
                                                                            "hide_fullscreen":1,
                                                                            "unmute_on_mouse":1,
                                                                            "continue_out_of_view":1,
                                                                            "autoplay":1,
                                                                            "blocked_autoplay_override_mode":1,
                                                                            "ad_mute":0
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        ]
                                                    }
                                                },
                                                "inread2":{
                                                    "targeting":{},
                                                    "dfpSizes":{
                                                        "0":[[1,1]],
                                                        "980":[[1,1]],
                                                        "1024":[[1,1]]
                                                    }
                                                }
        }
                                         
    }
};